### ISSUE TITLE
空心字体在哪里找的呀

### ISSUE THREAD

**Issue by zsnjuts** [mlvehr/mlvehr.github.io#1]
你好\~这个贺卡很漂亮，所以我也想仿照着做一个\~
但是我发现贺卡里面的空心字体好像只有那几个字，改成别的字就不是空心的了，这是为什么呢？贺卡里面空心字体是在哪里找的呢？

**Comment by mlvehr** [comment]
你好，很抱歉现在才看到😔

为了加载快速，只提取了关键文字来减小字体文件。
- 具体可以使用 [fontmin](http://ecomfe.github.io/fontmin/) 等工具
- 空心字体：**_文鼎香肠体_** 

可以修改 css 样式替换：[/styles/font.css](https://github.com/mlvehr/mlvehr.github.io/blob/795317cfbf5d75070a1f1d5770b4c542ceac5678/birthday/fuqiting/styles/font.css#L1)
